### ISSUE TITLE
APK Signature Scheme v2

### ISSUE THREAD

**Issue by eeriemyxi** [er2off/basic-android-app#1]
It does not work on A11+. I tried to make it work with the new signing process with no success. Do you plan to update this?

**Comment by er2off** [comment]
Yes, I have another makefile with aapt2 and d8 tools but it's currently not uploaded

**Comment by eeriemyxi** [comment]
> Yes, I have another makefile with aapt2 and d8 tools but it's currently not uploaded

That's great news. Will you update this one, or create a new repository for that one?

**Comment by er2off** [comment]
So I'm kinda sorry for 2 week delay but I finally got time to update repo. Now it should compile with modern tools and probably work with latest Android (I don't checked this on A14 but it works on Android 7)

https://github.com/er2off/basic-android-app/commit/8b3974ae3afadc906f7b4f4bed981271c0ab2290

**Comment by eeriemyxi** [comment]
> So I'm kinda sorry for 2 week delay but I finally got time to update repo. Now it should compile with modern tools and probably work with latest Android (I don't checked this on A14 but it works on Android 7)
> 
> [8b3974a](https://github.com/er2off/basic-android-app/commit/8b3974ae3afadc906f7b4f4bed981271c0ab2290)

Great. I will check it out this week. Thank you!
