### ISSUE TITLE
Compilation Errors on MainActivity.java

### ISSUE THREAD

**Issue by eeriemyxi** [er2off/basic-android-app#2]
```ini
# Key to sign the app
KEY_PATH = debug.keystore
KEY_NAME = androiddebugkey
KEY_PASS = android

# SDK tools version
SDK_VER   = 24
SDK       = 24.0.3

# Roots
SDK_ROOT  = ~/.android-sdk/Sdk
JAVA_HOME?= /usr/lib/jvm/java-1.11.0-openjdk-amd64

# Android framework, contains API
VEDBASE   = $(SDK_ROOT)/platforms/android-$(SDK_VER)/android.jar

# Tools
ADB       = $(SDK_ROOT)/platform-tools/adb
PM        = $(ADB) # same functionality on pc
MONKEY    = $(ADB) shell monkey
AAPT2     = $(SDK_ROOT)/build-tools/$(SDK)/aapt2
APKSIGNER = $(SDK_ROOT)/build-tools/$(SDK)/apksigner
D8        = $(SDK_ROOT)/build-tools/$(SDK)/d8
ZIPALIGN  = $(SDK_ROOT)/build-tools/$(SDK)/zipalign
JARSIGNER = $(JAVA_HOME)/bin/jarsigner
JAR       = $(JAVA_HOME)/bin/jar
JAVAC     = $(JAVA_HOME)/bin/javac
```
I moved `conf/config.example.mk` to `config.mk` as instructed and the only change I made was changing the `SDK_ROOT` path. I installed the same SDK version as used in the default config file. I also installed the same openjdk JVM version from Ubuntu Jammy repositories. I get the following errors when running `make`:
```
myxi :: /tmp/basic-android-app ‹main*› » make
Compiling src/com/example/hello/MainActivity.java
src/com/example/hello/MainActivity.java:3: error: package android.app does not exist
import android.app.Activity;
                  ^                                                                                                                                                     %src/com/example/hello/MainActivity.java:4: error: package android.os does not exist
import android.os.Bundle;
                 ^
src/com/example/hello/MainActivity.java:6: error: cannot find symbol
public class MainActivity extends Activity {
                                  ^
  symbol: class Activity
src/com/example/hello/MainActivity.java:8: error: cannot find symbol
  public void onCreate(Bundle savedInstanceState) {
                       ^
  symbol:   class Bundle
  location: class MainActivity
src/com/example/hello/MainActivity.java:7: error: method does not override or implement a method from a supertype
  @Override
  ^
src/com/example/hello/MainActivity.java:9: error: cannot find symbol
    super.onCreate(savedInstanceState);
    ^
  symbol:   variable super
  location: class MainActivity
src/com/example/hello/MainActivity.java:10: error: package R does not exist
    setContentView(R.layout.main);
                    ^
7 errors
make: *** [Makefile:77: work/java/com/example/hello/MainActivity.class] Error 1
```

BTW, I am not sure if this is intended, but `config.example.mk` is missing `AAPT2JAR` definition that is used in the `Makefile`.

**Comment by er2off** [comment]
You forgot to install `platforms;android-24` in sdkmanager? Newer SDKs still can build for old Android versions if you want so you can install newer version instead (such as `platforms;android-34`) and set into `SDK_VER`

Also I forgot to upgrade build-tools version here and in 24.0.3 there's no d8 utility. You may install `build-tools;34.0.0` or other version and set this value into `SDK` variable.

> but `config.example.mk` is missing `AAPT2JAR` definition that is used in the `Makefile`.

OMG, I forgot and only tested this in termux, this value is the same as `VEDBASE`, that's because in termux `usr/share/java/android-24.jar` doesn't contain resources.arsc (but everything is already included in Google's build-tools SDK)

**Comment by eeriemyxi** [comment]
Because,
> in 24.0.3 there's no d8 utility.

I ran, 
```
  ./sdkmanager --install "platforms;android-34"
  ./sdkmanager --install "build-tools;34.0.0"
```
Then, based on your input,  I changed the config file to the following:
```ini
# Key to sign the app
KEY_PATH = debug.keystore
KEY_NAME = androiddebugkey
KEY_PASS = android

# SDK tools version
SDK_VER   = 34
SDK       = 34.0.0

# Roots
SDK_ROOT  = ~/.android-sdk/Sdk
JAVA_HOME?= /usr/lib/jvm/java-1.11.0-openjdk-amd64

# Android framework, contains API
VEDBASE   = $(SDK_ROOT)/platforms/android-$(SDK_VER)/android.jar
AAPT2JAR  = $(SDK_ROOT)/platforms/android-$(SDK_VER)/android.jar

# Tools
ADB       = $(SDK_ROOT)/platform-tools/adb
PM        = $(ADB) # same functionality on pc
MONKEY    = $(ADB) shell monkey
AAPT2     = $(SDK_ROOT)/build-tools/$(SDK)/aapt2
APKSIGNER = $(SDK_ROOT)/build-tools/$(SDK)/apksigner
D8        = $(SDK_ROOT)/build-tools/$(SDK)/d8
ZIPALIGN  = $(SDK_ROOT)/build-tools/$(SDK)/zipalign
JARSIGNER = $(JAVA_HOME)/bin/jarsigner
JAR       = $(JAVA_HOME)/bin/jar
JAVAC     = $(JAVA_HOME)/bin/javac
``` 

Running `make`, I have only one error remaining:
```
myxi :: Documents/trash/basic-android-app ‹main*› » make
Compiling src/com/example/hello/MainActivity.java
src/com/example/hello/MainActivity.java:10: error: package R does not exist
    setContentView(R.layout.main);
                    ^
1 error
make: *** [Makefile:77: work/java/com/example/hello/MainActivity.class] Error 1
```

I am not sure what is causing it. I am sorry if this is too basic, but I have no idea how all this works yet. I was planning on learning the details once I have a working version of the template available.

**Comment by er2off** [comment]
> package R does not exist

How it skipped resources generation (`work/res.apk`)?

**Comment by eeriemyxi** [comment]
Seems like the earlier errors generated some files, and because of that, Makefile decided to skip those parts. I ran `make clean` and then ran `make` and it worked this time and `work/out.apk` was generated successfully. However `make deploy` did error:
```
myxi :: Documents/trash/basic-android-app ‹main*› » make deploy
Compiling resource res/drawable-xhdpi/icon.png
Compiling resource res/layout/main.xml
Compiling resource res/values/strings.xml
Generating res.apk and R.java
Compiling src/com/example/hello/MainActivity.java
Generating classes.dex
  adding: classes.dex (deflated 37%)
Failure [DELETE_FAILED_INTERNAL_ERROR]
make: *** [Makefile:88: deploy] Error 1
```
So, I shared the APK file to my device (A11) manually and installed it:
![Screenshot_2024-03-31-13-18-38-63_f1daee9170fda1df4088c67226246dc4](https://github.com/er2off/basic-android-app/assets/86738916/50ab16eb-069a-46e7-b1d5-152089be542d)

I am doing wireless debugging thing of A11+, maybe that has something to do with it.

**Comment by eeriemyxi** [comment]
That said, the original issue is resolved, so I am closing it. Thank you!
